target = appletv:12.1.1

INSTALL_TARGET_PROCESSES = PineBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = FLEXInjected

FLEXInjected_FILES = Tweak.x
FLEXInjected_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
