
default_platform(:ios)

lane :exportXCFramework do |options|
  create_xcframework(
    project: "FLEX.xcodeproj",
    scheme: 'FLEX',
    destinations: ['iOS'],
    xcframework_output_directory: 'build/',
    enable_bitcode: false
  )
end